[package]
name = "waylock"
version = "0.1.0"

authors = ["Isaac Freund <ifreund@ifreund.xyz>"]
description = "A simple screenlocker for wayland compositors."
edition = "2018"
keywords = ["wayland", "screenlocker"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ifreund/waylock"

[dependencies]
ansi_term = "0.12"
cairo-rs = "0.8"
clap = "2"
humantime = "2"
log = { version = "0.4", features = ["std"] }
pam = "0.7"
serde = { version = "1", features = ["derive"] }
smithay-client-toolkit = "0.8"
toml = "0.5"
users = "0.9"
xdg = "2"
